export enum Feature {
  CAT = 'CAT',
  ROLE = 'ROLE',
}

export enum Action {
  // CAT
  CAT_FEATURE_CREATE = 'CAT_FEATURE_CREATE',
  CAT_FEATURE_UPDATE = 'CAT_FEATURE_UPDATE',
  CAT_FEATURE_READ = 'CAT_FEATURE_READ',
  CAT_FEATURE_DELETE = 'CAT_FEATURE_DELETE',
  // ROLE
  ROLE_FEATURE_CREATE = 'ROLE_FEATURE_CREATE',
  ROLE_FEATURE_UPDATE = 'ROLE_FEATURE_UPDATE',
  ROLE_FEATURE_READ = 'ROLE_FEATURE_READ',
  ROLE_FEATURE_DELETE = 'ROLE_FEATURE_DELETE',
}
